# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

it:
  languageCode: it
  contentDir: content/it
  title: Alberto Parmiggiani
  params:
    description: Alberto Parmiggiani
  menu:
    main:
      - name: Home
        url: '#about'
        weight: 10
      # - name: Post
      #   url: '#posts'
      #   weight: 20
      - name: Progetti
        url: '#projects'
        weight: 30
      - name: Talks
        url: '#talks'
        weight: 40
      - name: Pubblicazioni
        url: '#featured'
        weight: 50
      - name: Contatti
        url: '#contact'
        weight: 60

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
